apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - echo
    - -n
    - hello; sleep 3600
    image: busybox
    name: busybox-1
    resources: {}
  - args:
    - echo
    - -n
    - hello; sleep 3600
    image: busybox
    name: busybox-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
