apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  initContainers:
  - image: busybox
    name: setup
    command: ['sh', '-c', 'wget -O google.com']
    containers:
  containers:
  - image: nginx
    name: complex-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
