apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - args:
    - consumer
    image: nginx
    name: pod
    resources: {}
    volumeMounts:
    - mountPath: /var/app
      name: test-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: test-volume
    secret:
      secretName: ext-service-secret
status: {}
