apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: empty
    emptyDir: {}
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: empty
      mountPath: /usr/share/nginx/html
  initContainers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'wget -O /work-dir/index.html http://neverssl.com/online']
    volumeMounts:
    - name: empty
      mountPath: /work-dir
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
