apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: complex-pod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: complex-pod
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  containers:
  - image: nginx
    name: complex-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
